# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c7750b4bd7df3e3d05c79acd69b723025a18b0b4036dd2f0056a2479634db55bc56e08ead4a82ac6855fe2274d792deb1e2b93a738e4122347c661f1ba0226ee

test:
  secret_key_base: 8fc64c43cfaf87372e7c9616260d47bad1ed9a2f685fa6e6f234b3c9df45f8b3fcc2dfcf6a82ad28bf80fa90ee4102cf329ca92893d5749f08f9f5741702d262

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
